### ISSUE TITLE
update to use gpt-3.5-turbo-instruct which plays as 1800

### ISSUE THREAD

**Issue by kusayuzayushko** [elh/0-0-0#1]
it should stop making illegal moves and pretty decent at positional play

**Comment by elh** [comment]
Amazing! I have been traveling and taking a long overdue break from Github 😅. Thanks for the note. 

I'll try to get around to it and will at mention you (if you don't mind) if you want to play around with it afterwards

**Comment by elh** [comment]
Implemented! It works really well. Without the constant illegal moves, it's actually fun to play now :)

Thanks @kusayuzayushko
